application: papertlogo--hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  application_readable: true

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /error
  static_files: static/error.txt
  upload: static/error.txt

- url: /moderate
  script: moderate.app

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /.*
  script: index.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
